server:
  port: 8208
  tomcat:
    connection-timeout: 7200000
  forward-headers-strategy: framework
  servlet:
      context-path: /api

spring:
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
    schemas: podcast_analyzer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/podcast_analyzer?serverTimezone=Europe/Kiev
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  mvc:
    async:
      request-timeout: 7200000
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: spring-ai-functions

#Pass API key as environment variable, e.g. -DPODCAST_INDEX_API_KEY=your-api-key
podcast-index:
  api:
    key: ${PODCAST_INDEX_API_KEY}
    secret: ${PODCAST_INDEX_API_SECRET}

qgrant:
  grpc-host: ${QDRANT_GRPC_HOST}
  api-key: ${QDRANT_API_KEY}

#Pass API key as environment variable, e.g. -DREPLICATE_API_KEY=your-api-key
replicate:
  api-key: ${REPLICATE_API_KEY}

#Pass API key as environment variable, e.g. -DHF_API_KEY=your-api-key
hugging-face:
  api-key: ${HF_API_KEY}

#Swagger
springdoc:
  api-docs:
    path: /docs

#Logging levels
logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.security.authentication: INFO
    org.springframework.boot: INFO
    org.springframework.ws: WARN
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: WARN
    com.podcast.ai: DEBUG